### ISSUE TITLE
Add callback 

### ISSUE THREAD

**Issue by behz4d** [ehpc/bootstrap-waitingfor#1]
Hello,

Thanks for this script.

How we can add callback function to this?
when I run `waitingDialog.hide();`, I want to `alert('1');` after it's gone hidden.

Right now if you do:
`waitingDialog.hide();`
`alert('1');`

You will get the alert while the modal is still there, I want to have the alert after the modal is completely hidden.

Thanks

**Comment by behz4d** [comment]
Figured this out by `hidden.bs.modal`.
Thanks anyway.

**Comment by behz4d** [comment]
This has caused me a serious problem, any working solution around?

**Comment by ehpc** [comment]
Hello, behz4d!

I've added a callback for your use case in commit c042c510290e3fdcda5f306203d0b5e8257f1ee4. You can now show the dialog as following:

		waitingDialog.show('Message', {
			onHide: function () {
				alert('1');
			}
		});

**Comment by accorinti** [comment]
The callback is not working if using the size option:
This works:
	waitingDialog.show('Message', {
                onHide: function () {
                   alert('1');
                }
          });
This doesn't:
	    waitingDialog.show('Message', {dialogSize: 'sm'}, {
						onHide: function () {
							alert('1');
						}
					});

:-/
