### ISSUE TITLE
Block only part of page.

### ISSUE THREAD

**Issue by ricardovsilva** [ehpc/bootstrap-waitingfor#16]
I want that waitingDialog.show() blocks only some part of my page, and not entire page. Like happens in http://bootsnipp.com/snippets/Oe5XM .
But I didn't found how do that.

**Comment by ehpc** [comment]
Well, the mechanism behind waitingfor is based on bootstrap modal dialog. So there is no way to specify such a behaviour. The effect you are referring to is due to the page with the dialog being enclosed in an iframe tag.

**Comment by ricardovsilva** [comment]
Unfortunately =/. I googled it, and seems that the only way to enforce modal into some specific did is with css (and this is why bootstrap team didn't implemented it yet). Anyway, congrats for easy use component. I'll fork your repo and still look for some solution.

**Comment by ehpc** [comment]
Thanks, I've made a milestone for this feature in the nearest future https://github.com/ehpc/bootstrap-waitingfor/milestones/Modal%20dialog%20for%20specific%20container
