### ISSUE TITLE
Typo when using importing with bower

### ISSUE THREAD

**Issue by darkurse** [ehpc/bootstrap-waitingfor#17]
Hi, just a small typo In bower.json.

{
"main": "src/**boostrap**-waitingfor.js",
}

it should be

{
"main": "src/**bootstrap**-waitingfor.js",
}

In my grunt file, I have task (bowerInstall) that inject Bower components into the HTML file. It looks at where the bower dependencies are and copies all the paths into my index.html as script or style imports. ( That stuff is made by Yeoman, not me )

Anyway, when importing your package, it failed to do so because of the typo above.

Thanks

**Comment by ehpc** [comment]
Hi, darkurse!

Thanks for the info. Fixed it in https://github.com/ehpc/bootstrap-waitingfor/commit/f1f02f1e26c4e2e3e7c76201b5b5e692e1dd9a51
