### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by mavillar** [ehpc/bootstrap-waitingfor#2]
It does not work in Safari.

**Comment by ehpc** [comment]
I've tested it on Safari 8.0.5 OSX Yosemite and it works. What version are you using?

**Comment by mavillar** [comment]
Exactly the same than you. The same OS and browser.

I have tested it in all bowsers and only in Safari do not show up.

**Comment by ehpc** [comment]
Can you attach a source code so I can reproduce the problem?
