### ISSUE TITLE
Adding support for Bootstrap 4

### ISSUE THREAD

**Issue by falkdav** [ehpc/bootstrap-waitingfor#25]
Hello, first off, nice plugin!

I want to know if would be possible to add support for Bootstrap 4 to this cool plugin.

Thanks!

**Comment by ehpc** [comment]
Hi, @falkdav! Thanks. Yeah sure, I'll try to test it in a couple of days.

**Comment by Lion-HC** [comment]
My temporary circumvention:
`define(['../lib/bootstrap-waitingfor/src/waitingfor'], function (waitingDialog) {
    var oldShow = waitingDialog.show;
    waitingDialog.show = function (message, options){
        if (!options) {
            options = {};
        }
        if (options.progressType) {
            options.progressType += ' progress-bar-striped progress-bar-animated';
        }
        else {
            options.progressType = 'striped progress-bar-animated';
        }
        oldShow(message, options);
    };
    return waitingDialog;
});`

**Comment by falkdav** [comment]
Hi @Lion-HC where should I put that code?

**Comment by Lion-HC** [comment]
It's something like wrapper for waitingfor to support bootstrap4.
It's if you using AMD (require.js)
If not  - you can override waitingDialog.show somewhere globally before using it.

**Comment by ehpc** [comment]
Fixed with https://github.com/ehpc/bootstrap-waitingfor/pull/26
