### ISSUE TITLE
fix settings.progressType class in bootstrap 4.1.1

### ISSUE THREAD

**Issue by vndevil** [ehpc/bootstrap-waitingfor#35]
remove line 94  `$dialog.find('.progress-bar').addClass('progress-bar-' + settings.progressType);`
add `$dialog.find('.progress-bar').addClass('bg-' + settings.progressType);`

**Comment by lukas-mertens** [comment]
I implemented this in #32, but the PR was never accepted. Most likely the maintainer abandoned this project. I don't know if it's time for a fork or if @ehpc is going to start working on the project again.

**Comment by lukas-mertens** [comment]
I made a fork with experimental bootstrap 4 support. Check it out [here](https://github.com/lukas-mertens/bootstrap-waitingfor). It is available through `npm install bootstrap-4-waitingfor`

**Comment by ehpc** [comment]
Merged #32 .
