### ISSUE TITLE
Bootstrap 4 hide not working if invoke immediately after show

### ISSUE THREAD

**Issue by alfadroid** [ehpc/bootstrap-waitingfor#37]
Hi,
I've try bootstrap-waitingfor with boostrap 4 but I found if I try to invoke hide() method, dialog not closing.
Problem I is fade can not permit to close it immediately.

I able to correct this issue by modify hide() method with this code at line 143:

```
hide: function () {
            if (typeof $dialog !== 'undefined') {
                $dialog.on('shown.bs.modal', function(e) {
                    $dialog.modal('hide');
                });
            }
        }
```

**Comment by ehpc** [comment]
@alfadroid Thanks, appreciate it :)
