### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Malavos** [ehpc/bootstrap-waitingfor#4]
Hey there,

For CDN control purposes, could we define versions numbers, and add a Changelog.md to the project. Can I help with that somehow?

**Comment by ehpc** [comment]
Hi!
Yes, you can help by supplying some useful links about your suggestion. Or you can create necessary changes yourself so I can review and merge them.

**Comment by Malavos** [comment]
@ehpc  alright! seems good! My notebook just broke and I sent it to support today. When it's back, I'll branch out and create the version file (.md) and insert the current version on the code. Let's keep the issue open so I can post whatever I'm doing here.

**Comment by ehpc** [comment]
Sure thing!

**Comment by ehpc** [comment]
I've published this plugin to bower and adapted semver.org semantics. So it is versioned now and this issue becomes obsolete.
